### ISSUE TITLE
Try to remove sync + send traits on implementations

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/flow#295]
Or, take a look at wasmer and what it would take to switch to it.

**Comment by andrewdavidmackenzie** [comment]
https://stackoverflow.com/questions/27957103/how-do-i-create-a-heterogeneous-collection-of-objects

For a collection of Trait objects for Implementations

**Comment by andrewdavidmackenzie** [comment]
Move Implementation trait back into flowrlib #420
- this maybe make it possible to implement the Send and Sync traits (local versions of them) for wasmi and remove dependency on my branch.

**Comment by andrewdavidmackenzie** [comment]
Fixed

**Comment by syrusakbary** [comment]
Note: we just added support for `Send` in Wasmer `Instance` https://github.com/wasmerio/wasmer/pull/807
